### ISSUE TITLE
amb64 Linux / Building tools directory fails

### ISSUE THREAD

**Issue by jwinarske** [linino/bathos-mcuio#2]
Building the tools directory fails with:

lilsprout@jollygreen:~/_bathos-mcuio-kl25z/tools$ make
gcc -ggdb -Wall -O2 -c lpclib.c -o lpclib.o
lpclib.c: In function ‘lpc_fd_gets’:
lpclib.c:132:3: error: unknown type name ‘fd_set’
   fd_set fds; struct timeval tv;
   ^
lpclib.c:132:30: error: storage size of ‘tv’ isn’t known
   fd_set fds; struct timeval tv;
                              ^
lpclib.c:133:3: warning: implicit declaration of function ‘FD_ZERO’ [-Wimplicit-function-declaration]
   FD_ZERO(&fds); FD_SET(fd, &fds);
   ^
lpclib.c:133:3: warning: implicit declaration of function ‘FD_SET’ [-Wimplicit-function-declaration]
lpclib.c:135:3: warning: implicit declaration of function ‘select’ [-Wimplicit-function-declaration]
   i = select(fd+1, &fds, NULL, NULL, &tv);
   ^
lpclib.c:132:30: warning: unused variable ‘tv’ [-Wunused-variable]
   fd_set fds; struct timeval tv;
                              ^
make: *** [lpclib.o] Error 1
lilsprout@jollygreen:~/_bathos-mcuio-kl25z/tools$ 

Adding the following header to lpclib.c fixes the problem:
#include <sys/select.h>

**Comment by ciminaghi** [comment]
On Tue, May 12, 2015 at 08:32:10PM -0700, Joel Winarske wrote:
> Building the tools directory fails with:
>
> lilsprout@jollygreen:~/_bathos-mcuio-kl25z/tools$ make
> gcc -ggdb -Wall -O2 -c lpclib.c -o lpclib.o
> lpclib.c: In function ???lpc_fd_gets???:
> lpclib.c:132:3: error: unknown type name ???fd_set???
>    fd_set fds; struct timeval tv;
>    ^
> lpclib.c:132:30: error: storage size of ???tv??? isn???t known
>    fd_set fds; struct timeval tv;
>                               ^
> lpclib.c:133:3: warning: implicit declaration of function ???FD_ZERO??? [-Wimplicit-function-declaration]
>    FD_ZERO(&fds); FD_SET(fd, &fds);
>    ^
> lpclib.c:133:3: warning: implicit declaration of function ???FD_SET??? [-Wimplicit-function-declaration]
> lpclib.c:135:3: warning: implicit declaration of function ???select??? [-Wimplicit-function-declaration]
>    i = select(fd+1, &fds, NULL, NULL, &tv);
>    ^
> lpclib.c:132:30: warning: unused variable ???tv??? [-Wunused-variable]
>    fd_set fds; struct timeval tv;
>                               ^
> make: *** [lpclib.o] Error 1
> lilsprout@jollygreen:~/_bathos-mcuio-kl25z/tools$ 
> 
> 
> Adding the following header to lpclib.c fixes the problem:
> #include <sys/select.h>
>
tools/ builds with one warning for me:

ciminaghi@dello:/home/develop/yun/riordino-git/bathos-mcuio/tools$ make
gcc -ggdb -Wall -O2 -c lpclib.c -o lpclib.o
ar rc liblpclib.a lpclib.o
gcc -ggdb -Wall -O2 dump.c -L. -llpclib -o dump
dump.c: In :
dump.c:36:15: warning:  set but not used [-Wunused-but-set-variable]
gcc -ggdb -Wall -O2 program.c -L. -llpclib -o program
gcc -ggdb -Wall -O2 progrom.c -L. -llpclib -o progrom
gcc -ggdb -Wall -O2 fix-checksum.c -L. -llpclib -o fix-checksum

However: man select says:

       /* According to POSIX.1-2001 */
       #include <sys/select.h>

       /* According to earlier standards */
       #include <sys/time.h>
       #include <sys/types.h>
       #include <unistd.h>

and:

grep select *.c
dump.c:#include <sys/select.h>
lpclib.c:               i = select(fd+1, &fds, NULL, NULL, &tv);
program.c:#include <sys/select.h>
program.c:              if (select(1, &fds, NULL, NULL, &tv) > 0) {
progrom.c:#include <sys/select.h>
progrom.c:              if (select(1, &fds, NULL, NULL, &tv) > 0) {


lpclib.c seems to be the only user of select not including <sys/select.h>,
and still builds for me if I add the include, so I think I'll add it.

Thanks
Davide

**Comment by ciminaghi** [comment]
On Tue, May 12, 2015 at 08:32:10PM -0700, Joel Winarske wrote:
> Building the tools directory fails with:
> 
> lilsprout@jollygreen:~/_bathos-mcuio-kl25z/tools$ make
> gcc -ggdb -Wall -O2 -c lpclib.c -o lpclib.o
> lpclib.c: In function ???lpc_fd_gets???:
> lpclib.c:132:3: error: unknown type name ???fd_set???
>    fd_set fds; struct timeval tv;
>    ^
> lpclib.c:132:30: error: storage size of ???tv??? isn???t known
>    fd_set fds; struct timeval tv;
>                               ^
> lpclib.c:133:3: warning: implicit declaration of function ???FD_ZERO??? [-Wimplicit-function-declaration]
>    FD_ZERO(&fds); FD_SET(fd, &fds);
>    ^
> lpclib.c:133:3: warning: implicit declaration of function ???FD_SET??? [-Wimplicit-function-declaration]
> lpclib.c:135:3: warning: implicit declaration of function ???select??? [-Wimplicit-function-declaration]
>    i = select(fd+1, &fds, NULL, NULL, &tv);
>    ^
> lpclib.c:132:30: warning: unused variable ???tv??? [-Wunused-variable]
>    fd_set fds; struct timeval tv;
>                               ^
> make: *** [lpclib.o] Error 1
> lilsprout@jollygreen:~/_bathos-mcuio-kl25z/tools$ 
> 
> 
> Adding the following header to lpclib.c fixes the problem:
> #include <sys/select.h>
>
I've just pushed a couple of commits fixing this thing and a "variable
set but not used" warning.


Thanks again
Davide

**Comment by jwinarske** [comment]
Thanks!
